version: 2
jobs:
  test:
    docker:
      - image: python:3.5
    steps:
        - checkout
        - run:
            name: Tests runner
            working_directory: swc_registry/
            command: |
              pip install -r ../requirements.txt
              pytest ../tests/
              $ENVSET = 'test'
  deploy:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = ersul4ik" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
              - test