version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    working_directory: /swcregistrypython
    steps:
        - checkout
        - run:
            name: Tests runner
            command: |
              ls
              python test.py
